# Generated by Django 4.1.5 on 2023-02-03 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modules.home.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('ben_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('benefitName', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='GoalFrequency',
            fields=[
                ('goal_freq_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goalFrequency', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GoalTiming',
            fields=[
                ('goal_timing_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goalTimings', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_goal_timings', models.IntegerField()),
                ('location', models.CharField(max_length=8000)),
                ('goal_frequency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.goalfrequency')),
                ('goal_timings_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.goaltiming')),
                ('user_id', models.ForeignKey(on_delete=models.SET(modules.home.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
